### ISSUE TITLE
Pillow should be 4.3.0

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image-wheels#7]
https://github.com/scikit-image/scikit-image-wheels/blob/19bf051316ef3aa6d07d1c4c801d18b0214ba5b7/.travis.yml#L8-L12

A while back we updated the minimum requirement of Pillow so that it would support jpeg decoding
https://github.com/scikit-image/scikit-image/blob/master/requirements/default.txt

I think this should be 4.3.0.

**Comment by stefanv** [comment]
Fixed in adaf37a51bb961e4b7e680fb2a6d17885755c7fd
