### ISSUE TITLE
OK to upload Python 3.7 wheels?

### ISSUE THREAD

**Issue by matthew-brett** [scikit-image/scikit-image-wheels#9]
Wheels built for Linux 64 bit, macOS, Windows 32 and 64 bit.

https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/

OK to upload these to PyPI?

**Comment by matthew-brett** [comment]
Well:

a) I think you're going to be testing master, not 0.14.0 - right?
b) in order for the wheels to get uploaded to PyPI, they had to pass their tests on travis-ci / Appveyor, so the testing is already done.  Can post logs if that's helpful.
c) even if the tests don't pass, a wheel is still preferable.  I can't see any advantage to forcing the user to do a source install, which might break, before they get a package with the same functionality as the wheel.

**Comment by soupault** [comment]
a) Both master and 0.14.1 (which is currently pretty similar to 0.14.0).

> b) Can post logs if that's helpful.

b) Yes, please. That would do it for me: if it is all green, I'm 👍 to upload. Otherwise, we can wait for 0.14.1 release with an official support of Python 3.7.

**Comment by matthew-brett** [comment]
Sure:

* Linux 64-bit : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/416029748
* macOS : I think I must have retriggered the successful build - here is a build that failed right at the end, with an uploading step that is nothing to do with scikit-image, but all the tests are passing: https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/416029754
* Windows 32-bit : https://ci.appveyor.com/project/matthew-brett/scikit-image-wheels/build/job/fi6o8kahwuycq1ap
* Windows 64-bit : https://ci.appveyor.com/project/matthew-brett/scikit-image-wheels/build/job/8g06mr9k46px4pex

Just to repeat - I can't myself think of a good argument for not having wheels, even if it wasn't true that the tests were passing, for the reasons I gave before. But if you can, then I'd be happy to hear it (honestly).

**Comment by matthew-brett** [comment]
Egor - are you reassured by the test logs?

**Comment by matthew-brett** [comment]
I propose to go ahead unless I hear otherwise from y'all in the next few hours.

**Comment by hmaarrfk** [comment]
The stuff built on Travis and Appveyor, I think it is fine.

**Comment by soupault** [comment]
@matthew-brett Thank you very much for the logs! Looks pretty safe, 👍 from me to go forward.

**Comment by matthew-brett** [comment]
Thanks for feedback - done now...
